function get_user_id(token) {
    return new Promise(function(resolve, reject) {

        fetch('https://api.spotify.com/v1/me', {
            headers: {
                'Authorization': 'Bearer ' + token
            }
        }).then(response => response.json()).then(response => resolve(response.id))
    })
}

function create_playlist(token, user_id, name_playlist) {
    return new Promise(function(resolve, reject) {
        const baseURL = "https://api.spotify.com/v1/users/" + user_id + "/playlists";
        const headers = {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json'
        };
        const body = JSON.stringify({
            "name": name_playlist,
            "description": "generated by deezer to spotify",
            "public": false
        })

        const options = {
            method: 'POST',
            headers: headers,
            body: body
        };
        fetch(baseURL, options).then(response => response.json()).then(response => resolve(response.id))
    })
}

async function fill_playlist(token, playlist_id, tracks) {
    let res_t = [];

    for (const track of tracks) {
        let t = await find_track(track, token);
        res_t.push(t);
    }
    for (let i = 0; i < res_t.length; i += 10) {
        const tracks = res_t.slice(i, i + 10);
        await add_track_playlist(token, playlist_id, tracks);
    }
}

function find_track(track, token) {
    return new Promise(function(resolve, reject) {
        url = 'https://api.spotify.com/v1/search?q=' + `${track.artist.name}%20${track.title}`
        url += "&type=track&limit=1"
        var options = {
            headers: {
                'Authorization': 'Bearer ' + token
            },
        }
        fetch(url, options)
        .then(response => response.json())
        .then(response => resolve(response.tracks.items[0]))
    })
}

function add_track_playlist(token, playlist_id, tracks) {
    return new Promise(function(resolve, reject) {
        const url = `https://api.spotify.com/v1/playlists/${playlist_id}/tracks`;
        const headers = {
            'Authorization': 'Bearer ' + token,
            'Content-Type': 'application/json',
        };

        const data = {
            uris: [],
        };
        for (let i = 0; i < tracks.length; i++) {
            data.uris.push(`spotify:track:${tracks[i].id}`);
        }

        const options = {
            method: 'POST',
            headers: headers,
            body: JSON.stringify(data),
        };

        fetch(url, options)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Failed to add track to playlist');
                }
                return response.json();
            })
            .then(response => {
                resolve(); // You can return the response from the API here if needed
            })
    });
}