function get_user_id(token) {
    return new Promise(function(resolve, reject) {

        fetch('https://api.spotify.com/v1/me', {
            headers: {
                'Authorization': 'Bearer ' + token
            }
        }).then(response => response.json()).then(response => resolve(response.id))
    })
}

function create_playlist(token, user_id, name_playlist) {
    return new Promise(function(resolve, reject) {
        const baseURL = "https://api.spotify.com/v1/users/"+ user_id + "/playlists";
        const headers = {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json'
        };
        const body = JSON.stringify({
            "name": name_playlist,
            "description": "generated by deezer to spotify",
            "public": false
        })

        const options = {
            method: 'POST',
            headers: headers,
            body: body
        };
        fetch(baseURL, options).then(response => response.json()).then(response => resolve(response.id))
    })
}

